### ISSUE TITLE
Gather data for ReSharper for C++

### ISSUE THREAD

**Issue by LegalizeAdulthood** [LegalizeAdulthood/refactor-test-suite#3]
Download [ReSharper for C++](https://www.jetbrains.com/resharper/features/cpp.html) and gather data on supported refactorings.

**Comment by nesteruk** [comment]
How do I upvote this? :)

**Comment by LegalizeAdulthood** [comment]
This one would probably be next for me.  Of course pull requests are gladly accepted :smile_cat:

**Comment by nesteruk** [comment]
If I do the tests and do as PR, would that be seen as biased considering I work for JB?

**Comment by LegalizeAdulthood** [comment]
The test suite is available to anyone and they can run the tests independently if they want.  I think it would be great if vendors contributed their own test runs on their own tools.  Let the tests do the talking, I say.  It would also be great feedback for me to know how easy it is for other people to run the tests.

**Comment by LegalizeAdulthood** [comment]
There are lots of tests that you could run, so where to start?  My suggestion is to start with Rename, then the extractors (Extract Function, Extract Method, etc.) and the Inliners (Inline Variable, Inline Method, etc.)
