### ISSUE TITLE
results/diff/CMS*.txt is missing for CreateMethodStub.cpp tests

### ISSUE THREAD

**Issue by moberhuber** [LegalizeAdulthood/refactor-test-suite#44]
Not sure if I'm looking in the wrong place? - I see tests have been executed in CLion for CreateMethodStub. But I am missing the results/diff/CMS*.txt with expected results. Same for CreateSetterMethod (CSM*.txt), Extract Constant )EC*.txt, probably more ?

**Comment by LegalizeAdulthood** [comment]
Thanks for the heads up.

I originally had the tests with no diffs and later added the results/diffs folder; if they are missing it's because I haven't generated the expectation manually and run a diff.
