### ISSUE TITLE
#TEST#: F529 markup is incorrect in Rename.cpp

### ISSUE THREAD

**Issue by moberhuber** [LegalizeAdulthood/refactor-test-suite#50]
Four #TEST# markups look wrong in Rename.cpp (found by extractAllCases.sh):

F529  | TBD
F530  | TBD
F550  | TBD
F551  | TBD

Expected these to be R529, R530, R550, R551 respectively.

**Comment by LegalizeAdulthood** [comment]
Yep, good catch!
