### ISSUE TITLE
Eclipse CDT results confuse the summary results generator

### ISSUE THREAD

**Issue by LegalizeAdulthood** [LegalizeAdulthood/refactor-test-suite#52]
The [summary results generator script](https://github.com/LegalizeAdulthood/refactor-test-suite/blob/master/results/processor/AllResults.js) expects the results files to look like:

```
## Refactoring Name
Case | Result
---- | ------
ID1 | Pass
ID2 | Failure
```

where there is no text between the refactoring name header and the start of the results table.

The new Eclipse CDT results sometimes have freeform markup after the refactoring name header.

We can either make the processing script smarter (probably best) or move the extra text from the result tables to the top of the results file, which allows freeform anything (probably easiest).

@moberhuber Your thoughts?

**Comment by moberhuber** [comment]
As a user, I'd prefer making the results generator smarter...

When I started looking at the testcases, not knowing each of the possible refactorings in detail yet, I was confused by the big blob of "instructions" that are currently in the CLion results for example. I find it much easier to understand if all information relevant for a particular refactoring is under that refactoring's bullet. That is: how to execute it, special notes and hints (which may apply to multiple specific test cases), followed by test results.

**Comment by moberhuber** [comment]
The fix actually turned out to be very simple, I've opened a PR.
